title: Nipuna Abeysinghe
logo: /Assets/img/Profile_pic_2.png
description:I design practical solutions and make them easy to understand
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
